'use client';

import { useState } from 'react';
import { Plus, X } from 'lucide-react';
import FormSortableList from './FormSortableList';

// Phase 8c structured editor for the WaiverScholarshipLanding
// summaryRows Json column — {category, max, status}[]. Three
// columns; status is constrained to a fixed enum (Active /
// Inactive) via a <select> so the admin can't accidentally
// type freeform values that bypass the public-page semantics.

type Status = 'Active' | 'Inactive';
const STATUSES: readonly Status[] = ['Active', 'Inactive'] as const;

type Row = { id: string; category: string; max: string; status: Status };

function genId() {
  return `sr_${Math.random().toString(36).slice(2, 11)}`;
}

function isStatus(v: unknown): v is Status {
  return v === 'Active' || v === 'Inactive';
}

function normalize(initial: unknown): Row[] {
  if (!Array.isArray(initial)) return [];
  return initial
    .filter((r): r is Record<string, unknown> => typeof r === 'object' && r !== null)
    .map((r) => ({
      id:       genId(),
      category: typeof r.category === 'string' ? r.category : '',
      max:      typeof r.max      === 'string' ? r.max      : '',
      // Legacy rows with any other string (or missing) coerce to
      // 'Active' — preserves prior seed data on first load.
      status:   isStatus(r.status) ? r.status : 'Active',
    }));
}

type Props = {
  name: string;
  initialValue: unknown;
};

export default function SummaryRowsEditor({ name, initialValue }: Props) {
  const [rows, setRows] = useState<Row[]>(() => normalize(initialValue));

  function add() {
    setRows([...rows, { id: genId(), category: '', max: '', status: 'Active' }]);
  }
  function remove(id: string) {
    setRows(rows.filter((r) => r.id !== id));
  }
  function updateText(id: string, field: 'category' | 'max', val: string) {
    setRows(rows.map((r) => (r.id === id ? { ...r, [field]: val } : r)));
  }
  function updateStatus(id: string, val: Status) {
    setRows(rows.map((r) => (r.id === id ? { ...r, status: val } : r)));
  }
  function reorder(orderedIds: string[]) {
    setRows(orderedIds.map((id) => rows.find((r) => r.id === id)!));
  }

  const serializable = rows
    .filter((r) => r.category.trim() || r.max.trim())
    .map(({ id: _id, ...rest }) => rest);

  return (
    <div className="space-y-2">
      {rows.length === 0 && (
        <p className="text-xs text-gray-500 italic">No summary rows yet.</p>
      )}
      <FormSortableList
        items={rows}
        getId={(r) => r.id}
        onReorder={reorder}
        renderItem={(r) => (
          <div className="bg-white border border-gray-200 rounded-lg p-3">
            <div className="grid grid-cols-1 md:grid-cols-[1fr_180px_140px_auto] gap-2 items-start">
              <Input label="Category" value={r.category}
                     onChange={(v) => updateText(r.id, 'category', v)}
                     placeholder="Sibling / Spouse / Parent" />
              <Input label="Maximum" value={r.max}
                     onChange={(v) => updateText(r.id, 'max', v)}
                     placeholder="10% per student" />
              <StatusSelect value={r.status} onChange={(v) => updateStatus(r.id, v)} />
              <button
                type="button"
                onClick={() => remove(r.id)}
                aria-label="Remove row"
                className="self-end p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded transition-colors"
              >
                <X size={16} />
              </button>
            </div>
          </div>
        )}
      />
      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={add}
          className="inline-flex items-center gap-1.5 text-xs font-medium text-accent hover:text-accent/80 transition-colors"
        >
          <Plus size={14} /> Add summary row
        </button>
        <p className="text-xs text-gray-500">
          SL numbers (1, 2, 3…) are auto-generated by the renderer.
        </p>
      </div>
      <input type="hidden" name={name} value={JSON.stringify(serializable)} />
    </div>
  );
}

function Input({
  label, value, onChange, placeholder,
}: { label: string; value: string; onChange: (v: string) => void; placeholder?: string }) {
  return (
    <div>
      <label className="block text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-0.5">
        {label}
      </label>
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full px-2.5 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-2 focus:ring-accent/40 focus:border-accent"
      />
    </div>
  );
}

function StatusSelect({
  value, onChange,
}: { value: Status; onChange: (v: Status) => void }) {
  return (
    <div>
      <label className="block text-[10px] font-semibold uppercase tracking-wider text-gray-500 mb-0.5">
        Status
      </label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value as Status)}
        className="w-full px-2.5 py-1.5 border border-gray-300 rounded text-sm bg-white focus:outline-none focus:ring-2 focus:ring-accent/40 focus:border-accent"
      >
        {STATUSES.map((s) => (
          <option key={s} value={s}>{s}</option>
        ))}
      </select>
    </div>
  );
}
